[env:adafruit_feather_esp32c6]
platform = espressif32
board = esp32-c6-devkitm-1
board_build.mcu = esp32c6
board_build.f_cpu = 160000000L
framework = arduino
extra_scripts = pre:fix_toolchain_path.py
upload_protocol = esptool
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1 -DARDUINO_USB_MODE=1

lib_deps =
    adafruit/Adafruit BNO08x   @ ^1.2.3
    adafruit/Adafruit BusIO    @ ^1.16.2
    adafruit/Adafruit NeoPixel @ ^1.12.3

